### ISSUE TITLE
save memory by using sparsity of E/R

### ISSUE THREAD

**Issue by j4yan** [OptimalDesignLab/ODLCommonTools.jl#2]
Currently, each dofs/nodes in the neighboring elements are used as stencil. This is not necessary for SBP-Gamma and SBP-DiagE because only dofs/nodes located on the interface contribute to the coupling. Besides, the bandwidth can also be reduced.

**Comment by jehicken** [comment]
Can you clarify, because, at least for second-order PDEs, you will need all the DOFs from the element in general.

**Comment by j4yan** [comment]
Sorry, I mean first order equations. For second-order PDEs, yes, we need all the DOFs in the neighboring elements.

**Comment by j4yan** [comment]
I am gonna work on diffusion terms in IBM, and have to build the sparsity pattern on my own. Then I just found that even for second-order PDEs, that we need all the DOFs from the neighbor elements is partially true. There are rows and columns in Jacobian, for off-diagonal block matrices only all DOFs are need in one dimension (column or row). Let's say if there are 'm' nodes on each face, and 'n' in each element, 'N_f' faces per element, then the memory cost that can be saved is 
  1 - (1+N_f (m/n)^2) / (1 + N_f) 
for 1st order PDEs, and 
  1 - (1+N_f [2m/n - (m/n)^2]) / (1+N_f) 
for 2nd order PDEs.

**Comment by JaredCrean2** [comment]
We do this now: https://github.com/OptimalDesignLab/ODLCommonTools.jl/blob/master/src/sparse.jl#L243
